library(dplyr)library(plyr)file <- "getdata_projectfiles_UCI HAR Dataset.zip"
## Download and unzip the dataset:if (!file.exists(file)){  fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"  download.file(fileURL, filename, method="curl")}  if (!file.exists("UCI HAR Dataset")) {   unzip(file) }
#load datasets
activity_labels <- read.table("UCI HAR Dataset/activity_labels.txt")activity_labels[,2]<-as.character(activity_labels[,2])features <- read.table("UCI HAR Dataset/features.txt")features[,2]<-as.character(features[,2])X_train <-read.table("UCI HAR Dataset/train/X_train.txt")Y_train <-read.table("UCI HAR Dataset/train/Y_train.txt")subject_train <-read.table("UCI HAR Dataset/train/subject_train.txt")
X_test <-read.table("UCI HAR Dataset/test/X_test.txt")Y_test <-read.table("UCI HAR Dataset/test/Y_test.txt")subject_test <-read.table("UCI HAR Dataset/test/subject_test.txt")
#1.Merges the training and the test sets to create one data set.#merge datasetsx_merge <- rbind(X_train,X_test)Y_merge <- rbind(Y_train,Y_test)subject_merge <- rbind(subject_train,subject_test)#asign coloumn names#2.Extracts only the measurements on the mean and standard deviation for each measurement. names(x_merge) <- features[,2]mean_and_std <-grep("-(mean|std)\\(\\)",features[,2])x_merge_meanstd <-x_merge[,mean_and_std]
#3.Uses descriptive activity names to name the activities in the data setY_merge_d <- inner_join(Y_merge,activity_labels, by="V1")Y_merge_d <-as.data.frame ( Y_merge_d[,2])#4.Appropriately labels the data set with descriptive variable names.names(Y_merge_d)<-"Activity"names(subject_merge) <- "subject"
# all_data <- cbind(x_merge_meanstd,Y_merge_d,subject_merge)
#5.From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.all_data_averages <- ddply(all_data, .(subject,Activity), function(x) colMeans(x[, 1:66]))
write.table(all_data_averages, "tidy.txt", row.name=FALSE)
